language: csharp
mono: none
dotnet: 5.0
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: true
branches:
  only:
  - master
script:
    - dotnet test test/Webenable.Hangfire.Contrib.Tests